"""
Agon — API URL routing.

All routes are mounted at /api/v1/ by the root agon/urls.py.

Auth endpoints (no authentication required):
    POST  /api/v1/auth/register/        — create a new account
    POST  /api/v1/auth/login/           — obtain JWT access + refresh tokens
    POST  /api/v1/auth/token/refresh/   — refresh an access token

Resource endpoints (authentication required unless noted):
    /api/v1/users/
    /api/v1/users/me/
    /api/v1/competitions/
    /api/v1/teams/
    /api/v1/teams/{id}/join/
    /api/v1/teams/{id}/leave/
    /api/v1/teams/{id}/members/
    /api/v1/submissions/
    /api/v1/profiles/
    /api/v1/profiles/me/
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    CompetitionViewSet,
    CustomTokenObtainPairView,
    RegisterView,
    StudentProfileViewSet,
    SubmissionViewSet,
    TeamViewSet,
    UserViewSet,
)

# ── DRF Router ─────────────────────────────────────────────────────────────────
router = DefaultRouter()
router.register(r"users", UserViewSet, basename="user")
router.register(r"competitions", CompetitionViewSet, basename="competition")
router.register(r"teams", TeamViewSet, basename="team")
router.register(r"submissions", SubmissionViewSet, basename="submission")
router.register(r"profiles", StudentProfileViewSet, basename="profile")

# ── URL patterns ───────────────────────────────────────────────────────────────
urlpatterns = [
    # Auth
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", CustomTokenObtainPairView.as_view(), name="auth-login"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="auth-token-refresh"),
    # Resource routes (generated by router)
    path("", include(router.urls)),
]
